import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/header";
import { FilterContextProvider } from "@/context/filterContext";
import { DataProvider } from "@/context/apiContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Raise - store",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className={inter.className}>
                <DataProvider>
                    <FilterContextProvider>
                        <Header/>
                        {children}
                    </FilterContextProvider>
                </DataProvider>
            </body>
            
        </html>
    );
}
