import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/header";
import { FilterContextProvider } from "@/context/filterContext";

//======================

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Raise - store",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="pt-BR">
            <body className={inter.className}>
                <FilterContextProvider>
                    <Header/>
                    {children}
                </FilterContextProvider>
            </body>
        </html>
    );
}
